### ISSUE TITLE
There is no "data/DOTA" in master project.

### ISSUE THREAD

**Issue by Iipython** [root12321/Rotation-Detect-yolov5_poly#4]
Hi , author
I want to execute your product according to readme,
but I found there are no configure files in your code.I cant run it. It seems no *.yaml at all. Could you upload yaml files?

**Comment by root12321** [comment]
> Hi , author I want to execute your product according to readme, but I found there are no configure files in your code.I cant run it. It seems no *.yaml at all. Could you upload yaml files?

i have been upload data folder and *.yaml
