### ISSUE TITLE
训练时出错No module named 'utils.loggers.wandb'

### ISSUE THREAD

**Issue by pangguanzhe344** [root12321/Rotation-Detect-yolov5_poly#5]
环境是pytorch1.7.1环境也配置好。
运行训练时$ python train.py --batch-size 4 --device 0出错
报错信息：
from utils.loggers.wandb.wandb_utils import WandbLogger
ModuleNotFoundError: No module named 'utils.loggers.wandb'
然后我从YOLOV5的项目里提取了wandb文件夹,报错消失。出现新的报错
from utils.general import LOGGER, check_dataset, check_file
ImportError: cannot import name 'LOGGER' from 'utils.general'。

**Comment by pwo123** [comment]
请问你解决这个问题了吗？我也很困扰这个问题
