### ISSUE TITLE
训练时  Labels ，P，R,map都是0。

### ISSUE THREAD

**Issue by pangguanzhe344** [root12321/Rotation-Detect-yolov5_poly#6]
## Additional context
作者你好，叨扰您了。
Starting training for 500 epochs...

     Epoch   gpu_mem       box       obj       cls     angle    labels  img_size
     0/499     3.33G   0.08736   0.07812    0.1614    0.3088        12      1280

     Epoch   gpu_mem       box       obj       cls     angle    labels  img_size
     1/499     3.34G   0.08028   0.05897    0.1066    0.3074        14      128
               Class     Images     Labels          P          R     mAP@.5 mAP@WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5 mAP@WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5 mAP@WARNING: NMS time limit 10.0s exceeded
               Class     Images     Labels          P          R     mAP@.5 mAP@
                 all         99          0          0          0          0          0

我训练时P，R,map都是0。运行detect.py没有检测框。val.py运行后也时pred.jpg没有框。我以为是我的数据集有问题（单类别）。按照双类别更改后，仍然无法解决问题。为此我又更换多类别的数据集（新的数据集）后，有了数值但是还是很低P=0.00203，map=0.000372（训练了41轮以后）.想问一下您试过在两类别或者单类别的数据集训练过吗？有没有类似的问题。
我还是怀疑是我的数据集的问题！哈哈。数据集太小了。

**Comment by root12321** [comment]
> ## ❔Question
> ## Additional context
> 作者你好，叨扰您了。 Starting training for 500 epochs...
> 
> ```
>  Epoch   gpu_mem       box       obj       cls     angle    labels  img_size
>  0/499     3.33G   0.08736   0.07812    0.1614    0.3088        12      1280
> 
>  Epoch   gpu_mem       box       obj       cls     angle    labels  img_size
>  1/499     3.34G   0.08028   0.05897    0.1066    0.3074        14      128
>            Class     Images     Labels          P          R     mAP@.5 mAP@WARNING: NMS time limit 10.0s exceeded
>            Class     Images     Labels          P          R     mAP@.5 mAP@WARNING: NMS time limit 10.0s exceeded
>            Class     Images     Labels          P          R     mAP@.5 mAP@WARNING: NMS time limit 10.0s exceeded
>            Class     Images     Labels          P          R     mAP@.5 mAP@
>              all         99          0          0          0          0          0
> ```
> 
> 我训练时P，R,map都是0。运行detect.py没有检测框。val.py运行后也时pred.jpg没有框。我以为是我的数据集有问题（单类别）。按照双类别更改后，仍然无法解决问题。为此我又更换多类别的数据集（新的数据集）后，有了数值但是还是很低P=0.00203，map=0.000372（训练了41轮以后）.想问一下您试过在两类别或者单类别的数据集训练过吗？有没有类似的问题。 我还是怀疑是我的数据集的问题！哈哈。数据集太小了。

多类别的你这边训了多少个epoch？

**Comment by pangguanzhe344** [comment]
50个以上

**Comment by root12321** [comment]
> 50个以上

代码有一些bug，正在排查，等排查完毕后更新新版本
