### ISSUE TITLE
label format

### ISSUE THREAD

**Issue by StarBlue98** [root12321/Rotation-Detect-yolov5_poly#7]
## ❔Question
前辈您好，请问您的模型采用四个角点： x1 y1 x2 y1... y4  点与点之间，是用空格分隔吗？还是用逗号呢？
请问 x1  y1 代表第一个点，是有要求是左上角的点吗？是否有规定 是顺时针标注还是逆时针呢？
求出的每一个点，是否需要进行归一化处理呢？（其实我看到一些其他前辈们写的代码需要做归一化处理，我不是很理解这么做的意义在哪里呢）

## Additional context
还有一个关于代码方面的问题：
在min_poly.py的第138-145行中，有：
                        max_shape = max(img.shape[1], img.shape[0])
                        # print("rect",rect)
                        c_x = ((i[0][0] + i[1][0]) / 2)
                        c_y = ((i[0][1] + i[1][1]) / 2)
                        w = abs((i[1][0] - i[0][0]))
                        h = abs((i[1][1] - i[0][1]))
                        points=[[c_x-w/2,c_y-h/2],[c_x+w/2,c_y-h/2],[c_x+w/2,c_y+h/2],[c_x-w/2,c_y+h/2]]

我不是很理解 w 和 h 的计算，为什么是要相减获得呢？因为我理解的是 w h 是标注文件中就已经给出了，为什么还要有这一步的求解过程呢？

我的疑惑有点多，还望前辈能够在百忙中抽空解惑，真的万分感谢前辈的指导！

**Comment by root12321** [comment]
> ## ❔Question
> 前辈您好，请问您的模型采用四个角点： x1 y1 x2 y1... y4 点与点之间，是用空格分隔吗？还是用逗号呢？ 请问 x1 y1 代表第一个点，是有要求是左上角的点吗？是否有规定 是顺时针标注还是逆时针呢？ 求出的每一个点，是否需要进行归一化处理呢？（其实我看到一些其他前辈们写的代码需要做归一化处理，我不是很理解这么做的意义在哪里呢）
> 
> ## Additional context
> 还有一个关于代码方面的问题： 在min_poly.py的第138-145行中，有： max_shape = max(img.shape[1], img.shape[0]) # print("rect",rect) c_x = ((i[0][0] + i[1][0]) / 2) c_y = ((i[0][1] + i[1][1]) / 2) w = abs((i[1][0] - i[0][0])) h = abs((i[1][1] - i[0][1])) points=[[c_x-w/2,c_y-h/2],[c_x+w/2,c_y-h/2],[c_x+w/2,c_y+h/2],[c_x-w/2,c_y+h/2]]
> 
> 我不是很理解 w 和 h 的计算，为什么是要相减获得呢？因为我理解的是 w h 是标注文件中就已经给出了，为什么还要有这一步的求解过程呢？
> 
> 我的疑惑有点多，还望前辈能够在百忙中抽空解惑，真的万分感谢前辈的指导！

1.是用空格分割的，
2.点的顺序按照左上，右上，右下，左下来的，
3.需要进行归一化处理，归一化的目的是为了训练加速收敛。
4.这里的w和h是计算target的w和h，目的是转换成四点坐标。
另外代码训练存在一点bug，目前我还没有排查到

**Comment by StarBlue98** [comment]
cool! 坐等您的代码，加油！
